# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

APPLY_FIXES: all
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

ENABLE:
  - ACTION
  - BASH
  - DOCKERFILE
  - EDITORCONFIG
  - MARKDOWN
  - YAML

DISABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - YAML_V8R

BASH_SHELLCHECK_ARGUMENTS: "-f gcc"
EDITORCONFIG_EDITORCONFIG_CHECKER_ARGUMENTS: "-f gcc"

POST_COMMANDS:
  - command: find . -user root -group root -exec chown ${USER}:${GROUP} {} \;
    cwd: workspace
